apiVersion: v1
kind: Service
metadata:
  name: app-a-service
  namespace: my-apps
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

