apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  namespace: my-apps
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: <your-docker-registry>/app-a:latest  # Use the latest tag
        imagePullPolicy: Always  # Always pull the latest image
        ports:
        - containerPort: 5000
        env:
        - name: AUTH_SERVICE_URL
          value: "http://app-b-service:5001/auth"  # Pointing to app-b for authentication

