apiVersion: v1
kind: Service
metadata:
  name: app-b-service
  namespace: my-apps
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

